name: doeat
description: A location based food sharing and/or helping app. (Flutter)

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # provider model
  provider: ^3.1.0+1
  intl: ^0.16.1
  # theme animation
  animated_theme_switcher: ^1.0.5
  # firebase login
  firebase_auth:
  google_sign_in: ^4.4.4
  # firebase data
  firebase_messaging: 6.0.13
  firebase_storage: ^3.0.6
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  cloud_firestore: ^0.12.9+4
  # shared preference
  shared_preferences: ^0.5.7
  # caching
  cached_network_image: ^2.1.0+1
  #toast
  fluttertoast: ^3.1.3
  # image picker
  image_picker: ^0.6.1+8
  # notification
  flutter_local_notifications: ^1.4.0
  # image view (full screen)
  photo_view: ^0.5.0
  # giphy support
  giphy_picker: ^1.0.4
  giphy_client: ^0.2.0
  # tooltip
  popup_menu: ^1.0.5
  # slide list
  flutter_slidable: ^0.5.4
  # stickey header
  sticky_headers: ^0.1.8
  # google map
  google_maps_flutter: ^0.5.27+1
#  location: ^3.0.2
  geolocator: ^3.0.1
  location: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/